name: Build and Test wxWidgets Project

on:
  push:
    branches: [ "cmake_branch" ]
  pull_request:
    branches: [ "cmake_branch" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtk-3-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libcurl4-openssl-dev \
          libwebkit2gtk-4.0-dev \
          libpng-dev \
          libjpeg-turbo8-dev \
          libtiff-dev \
          zlib1g-dev \
          libwxgtk3.0-gtk3-dev \
          wx-common

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/UICode -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build wxWidgets Project
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
